using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.1.1.1")]
[assembly: AssemblyFileVersionAttribute("0.1.1.1")]
[assembly: AssemblyCopyrightAttribute("Copyright 2015")]
[assembly: AssemblyProductAttribute("DeathStar Imperator")]
[assembly: AssemblyCompanyAttribute("Doc Rinehart")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.1.1.1")]
